name: publish

on: [push]

jobs:
  publish-hello-ghcr-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHR_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/darthvader2/ghcr-test:latest
        docker push ghcr.io/darthvader2/ghcr-test:latest
